name: Cypress E2E Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run Cypress tests
        run: pnpm run e2e-cy
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: cypress/
          retention-days: 30
